spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:30642/smile_ums?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: '000000'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat

mybatis-plus:
  type-aliases-package: com.smile.**
  mapper-locations: classpath:/xml/*.xml
springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true