knife4j:
  enable: false
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: false
        add-to-simple-url-handler-mapping: true
      routes:
        - id: smile-system-doc
          uri: lb://smile-system
          predicates:
            - Path=/system/**
          filters:
            - RewritePath=/system(?<segment>/?.*), $\{segment}
        - id: smile-member-doc
          uri: lb://smile-member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member(?<segment>/?.*), $\{segment}
        - id: smile-auth-doc
          uri: lb://smile-auth
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/?.*), $\{segment}

