spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: false
        add-to-simple-url-handler-mapping: true



      routes:
      - id: smile-member
        uri: lb://smile-member
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/?(?<segment>.*), /$\{segment}

      - id: smile-auth
        uri: lb://smile-auth
        predicates:
          - Path=/auth/**
        filters:
          - RewritePath=/auth/?(?<segment>.*), /$\{segment}




management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway